### ISSUE TITLE
Not enough balance to transfer

### ISSUE THREAD

**Issue by Resistenttt** [Web3ViraLabs/Solana-Auto-Transfer#4]
It does not work, at startup it writes Not enough balance to transfer, although the keys are inserted correctly and the balance corresponds

**Comment by oxy-Op** [comment]
Please make sure you have,

-  Added `PRIVATE_KEY="YOUR_SECRET_KEY"` (in quotes) in `.env` 
-  Have more than 0.003 SOL in your wallet

For further debug, would you like to share your public key

**Comment by Web3ViraLabs** [comment]
line no. 9 change: @Resistenttt 

    web3.clusterApiUrl('devnet'),
  
  to 
  
    web3.clusterApiUrl('mainnet-beta'),

**Comment by Resistenttt** [comment]
Everything worked, thank you very much)
